version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Build Starting on `date`
      - cd DeployServer
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./Bitharbor_server/build/libs/*.jar)
artifacts:
  files:
    - Bitharbor_server/build/libs/*.jar
    - Bitharbor_server/scripts/**
    - Bitharbor_server/appspec.yml
  discard-paths: yes